admin:
  user: gimmeadmin
  password: gimmeadmin
port: 8080
secret: secret
s3:
  url: minio:9000
  key: minioadmin
  secret: minioadmin
  bucketName: gimme
  location: eu-west-1
  ssl: false
metrics: true